### ISSUE TITLE
Why shouldn't this be used?

### ISSUE THREAD

**Issue by christianbundy** [dutc/didyoumean#1]
I don't do Python development, but this looks like an interesting project. Is there something fundamentally janky about what you're doing? Thanks!

**Comment by dutc** [comment]
It's not a particularly useful feature in practice. Misspellings resulting in AttributeErrors are generally caught pretty quickly, and this addition to standard error reporting would mostly be useful in interactive settings where the mistake would be obvious. 

(Note that linting tools like PyFlakes already do a fairly good job of picking up on NameErrors, which result from using variables that don't exist.)

I have two other approaches to supplement error reporting with spelling suggestions (https://gist.github.com/dutc/3f2c79048d95287be138) that are a little less ‘janky.’

What makes this approach particularly offensive are:
- I implement this by hooking into a C function in the Python interpreter itself, `PyObject_GetAttr`: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/didyoumean.c#L147
- I find the function, unprotect its memory page, then clobber first few assembly instructions with a jump: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/hook.c#L29
- I need to jump to an absolute address, since I don't want to (or can't?) calculate the relative addresses. I don't believe I can do this with a `push` and a `ret` or with a regular `call`, so I use a `jmp` instruction. The `jmp` instruction won't take an absolute address as an immediate value, so I have to use the `%rax` register: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/hook.c#L12
- Since I'm using this register, I have to save & restore its value. In the hooking code, I save its value with a `push %rax`. In order to restore its value, I have patch the assembly for the hook function to stick a `pop %rax` at the top before any other instructions: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/hook.c#L50
- In order to figure out the candidates for the spelling correction, I need to call `dir` on the object. But `dir` calls`PyObject_GetAttr` internally, and those calls can themselves trigger exceptions. In order to avoid this unbounded recursion, I have to implement a parallel code-path for `dir` by creating a `safe_PyObject_Dir`: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/safe_PyObject_Dir.c
- In some builds of Python, the internal CFunction which provides the Python builtin function `getattr()`, `builtin_getattr`, is compiled without explicit calls to `PyObject_GetAttr`. In order to hook into these `getattr` calls, I need to patch the builtin module. But because someone could have already gotten a handle on `getattr`, I need to directly patch the function: https://github.com/dutc/didyoumean/blob/2c9f01d03c1574f93155df6c6e3b59b914bacf20/src/didyoumean.c#L150

This approach is probably not portable, and it's definitely not a good idea.

However, figuring out all these small problems was a great way to put some low-level knowledge to use!
